[package]
name = "bevy_ui_styled_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
bevy = { version = "0.9", default-features = false, features = [
    "bevy_ui",
    "render",
] }
anyhow = "^1.0"
